artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  file_path: moniepoint/monie_point_data/synthetic_dirty_transaction_logs.csv
  # local_data_file: artifacts/data_ingestion/anomaly_detection.csv
  local_data_dir: artifacts/data_ingestion
  clean_data_path: artifacts/data_ingestion/cleaned_anomaly_detection.csv
 

data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_ingestion/anomaly_detection.csv
  data_path2: artifacts/data_ingestion/cleaned_anomaly_detection.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/anomaly_detection.csv



# model_trainer:
#   root_dir: artifacts/model_trainer
#   train_data_path: artifacts/data_transformation/train.csv
#   test_data_path: artifacts/data_transformation/test.csv
#   model_name: model.joblib



# model_evaluation:
#   root_dir: artifacts/model_evaluation
#   test_data_path: artifacts/data_transformation/test.csv
#   model_path: artifacts/model_trainer/model.joblib
#   metric_file_name: artifacts/model_evaluation/metrics.json






